obj/altera_avalon_lcd_16207_fd.o:  \
 /opt/altera/ip/altera/sopc_builder_ip/altera_avalon_lcd_16207/HAL/src/altera_avalon_lcd_16207_fd.c \
  /opt/altera/ip/altera/nios2_ip/altera_nios2/HAL/inc/alt_types.h \
  /opt/altera/nios2eds/components/altera_hal/HAL/inc/sys/alt_dev.h \
  system_description/system.h \
  /opt/altera/nios2eds/components/altera_hal/HAL/inc/sys/alt_llist.h \
  /opt/altera/ip/altera/nios2_ip/altera_nios2/HAL/inc/alt_types.h \
  /opt/altera/nios2eds/components/altera_hal/HAL/inc/priv/alt_dev_llist.h \
  /opt/altera/nios2eds/components/altera_hal/HAL/inc/sys/alt_llist.h \
  /opt/altera/ip/altera/nios2_ip/altera_nios2/HAL/inc/alt_types.h \
  /opt/altera/ip/altera/sopc_builder_ip/altera_avalon_lcd_16207/HAL/inc/altera_avalon_lcd_16207.h \
  /opt/altera/nios2eds/bin/nios2-gnutools/H-i686-pc-linux-gnu/bin/../lib/gcc/nios2-elf/3.4.6/include/stddef.h \
  /opt/altera/nios2eds/components/altera_hal/HAL/inc/sys/alt_alarm.h \
  /opt/altera/nios2eds/components/altera_hal/HAL/inc/sys/alt_llist.h \
  /opt/altera/nios2eds/components/altera_hal/HAL/inc/priv/alt_alarm.h \
  /opt/altera/nios2eds/components/altera_hal/HAL/inc/os/alt_sem.h \
  /opt/altera/nios2eds/components/altera_hal/HAL/inc/priv/alt_no_error.h \
  /opt/altera/ip/altera/sopc_builder_ip/altera_avalon_lcd_16207/HAL/inc/altera_avalon_lcd_16207_fd.h \
  /opt/altera/nios2eds/components/altera_hal/HAL/inc/sys/alt_dev.h
