obj/alt_sys_init.o: system_description/alt_sys_init.c \
  system_description/system.h \
  /opt/altera/nios2eds/components/altera_hal/HAL/inc/sys/alt_sys_init.h \
  /opt/altera/ip/altera/nios2_ip/altera_nios2/HAL/inc/sys/alt_irq.h \
  /opt/altera/nios2eds/bin/nios2-gnutools/H-i686-pc-linux-gnu/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/errno.h \
  /opt/altera/nios2eds/bin/nios2-gnutools/H-i686-pc-linux-gnu/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/sys/errno.h \
  /opt/altera/nios2eds/bin/nios2-gnutools/H-i686-pc-linux-gnu/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/sys/reent.h \
  /opt/altera/nios2eds/bin/nios2-gnutools/H-i686-pc-linux-gnu/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/_ansi.h \
  /opt/altera/nios2eds/bin/nios2-gnutools/H-i686-pc-linux-gnu/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/newlib.h \
  /opt/altera/nios2eds/bin/nios2-gnutools/H-i686-pc-linux-gnu/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/sys/config.h \
  /opt/altera/nios2eds/bin/nios2-gnutools/H-i686-pc-linux-gnu/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/machine/ieeefp.h \
  /opt/altera/nios2eds/bin/nios2-gnutools/H-i686-pc-linux-gnu/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/sys/_types.h \
  /opt/altera/nios2eds/bin/nios2-gnutools/H-i686-pc-linux-gnu/bin/../lib/gcc/nios2-elf/3.4.6/include/stddef.h \
  /opt/altera/ip/altera/nios2_ip/altera_nios2/HAL/inc/nios2.h \
  /opt/altera/ip/altera/nios2_ip/altera_nios2/HAL/inc/alt_types.h \
  system_description/system.h \
  /opt/altera/ip/altera/nios2_ip/altera_nios2/HAL/inc/priv/alt_legacy_irq.h \
  system_description/system.h \
  /opt/altera/ip/altera/nios2_ip/altera_nios2/HAL/inc/nios2.h \
  /opt/altera/ip/altera/nios2_ip/altera_nios2/HAL/inc/alt_types.h \
  /opt/altera/ip/altera/nios2_ip/altera_nios2/HAL/inc/sys/alt_irq.h \
  /opt/altera/ip/altera/nios2_ip/altera_nios2/HAL/inc/nios2.h \
  /opt/altera/ip/altera/sopc_builder_ip/altera_avalon_lcd_16207/HAL/inc/altera_avalon_lcd_16207.h \
  /opt/altera/nios2eds/components/altera_hal/HAL/inc/sys/alt_alarm.h \
  /opt/altera/nios2eds/components/altera_hal/HAL/inc/sys/alt_llist.h \
  /opt/altera/ip/altera/nios2_ip/altera_nios2/HAL/inc/alt_types.h \
  /opt/altera/nios2eds/components/altera_hal/HAL/inc/priv/alt_alarm.h \
  /opt/altera/ip/altera/nios2_ip/altera_nios2/HAL/inc/alt_types.h \
  /opt/altera/nios2eds/components/altera_hal/HAL/inc/os/alt_sem.h \
  /opt/altera/nios2eds/components/altera_hal/HAL/inc/priv/alt_no_error.h \
  /opt/altera/ip/altera/sopc_builder_ip/altera_avalon_lcd_16207/HAL/inc/altera_avalon_lcd_16207_fd.h \
  /opt/altera/nios2eds/components/altera_hal/HAL/inc/sys/alt_dev.h \
  system_description/system.h \
  /opt/altera/nios2eds/components/altera_hal/HAL/inc/sys/alt_llist.h \
  /opt/altera/nios2eds/components/altera_hal/HAL/inc/priv/alt_dev_llist.h \
  /opt/altera/nios2eds/components/altera_hal/HAL/inc/sys/alt_llist.h \
  /opt/altera/ip/altera/sopc_builder_ip/altera_avalon_cfi_flash/HAL/inc/altera_avalon_cfi_flash.h \
  /opt/altera/ip/altera/nios2_ip/altera_nios2/HAL/inc/alt_types.h \
  /opt/altera/nios2eds/components/altera_hal/HAL/inc/sys/alt_flash_dev.h \
  /opt/altera/nios2eds/components/altera_hal/HAL/inc/sys/alt_flash_types.h \
  /opt/altera/nios2eds/components/altera_hal/HAL/inc/sys/alt_llist.h \
  /opt/altera/ip/altera/sopc_builder_ip/altera_avalon_sysid/HAL/inc/altera_avalon_sysid.h \
  /opt/altera/ip/altera/nios2_ip/altera_nios2/HAL/inc/alt_types.h \
  /opt/altera/ip/altera/sopc_builder_ip/altera_avalon_timer/HAL/inc/altera_avalon_timer.h \
  /opt/altera/nios2eds/bin/nios2-gnutools/H-i686-pc-linux-gnu/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/string.h \
  /opt/altera/nios2eds/bin/nios2-gnutools/H-i686-pc-linux-gnu/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/_ansi.h \
  /opt/altera/ip/altera/nios2_ip/altera_nios2/HAL/inc/alt_types.h \
  /opt/altera/nios2eds/components/altera_hal/HAL/inc/sys/alt_dev.h \
  /opt/altera/ip/altera/nios2_ip/altera_nios2/HAL/inc/sys/alt_warning.h \
  /opt/altera/ip/altera/sopc_builder_ip/altera_avalon_jtag_uart/HAL/inc/altera_avalon_jtag_uart.h \
  /opt/altera/nios2eds/components/altera_hal/HAL/inc/sys/alt_alarm.h \
  /opt/altera/ip/altera/nios2_ip/altera_nios2/HAL/inc/sys/alt_warning.h \
  /opt/altera/nios2eds/components/altera_hal/HAL/inc/os/alt_sem.h \
  /opt/altera/nios2eds/components/altera_hal/HAL/inc/os/alt_flag.h \
  /opt/altera/ip/altera/sopc_builder_ip/altera_avalon_jtag_uart/HAL/inc/altera_avalon_jtag_uart_fd.h \
  /opt/altera/nios2eds/components/altera_hal/HAL/inc/sys/alt_dev.h \
  /opt/altera/ip/altera/sopc_builder_ip/altera_avalon_uart/HAL/inc/altera_avalon_uart.h \
  /opt/altera/nios2eds/components/altera_hal/HAL/inc/sys/termios.h \
  /opt/altera/ip/altera/nios2_ip/altera_nios2/HAL/inc/sys/alt_warning.h \
  /opt/altera/nios2eds/components/altera_hal/HAL/inc/os/alt_sem.h \
  /opt/altera/nios2eds/components/altera_hal/HAL/inc/os/alt_flag.h \
  /opt/altera/ip/altera/nios2_ip/altera_nios2/HAL/inc/alt_types.h \
  /opt/altera/ip/altera/sopc_builder_ip/altera_avalon_uart/HAL/inc/altera_avalon_uart_fd.h \
  /opt/altera/nios2eds/components/altera_hal/HAL/inc/sys/alt_dev.h
