# TCL File Generated by Component Editor 7.2 on:
# Thu Nov 01 20:32:10 CST 2007
# DO NOT MODIFY

set_source_file "DM9000A_IF.v"
set_module "DM9000A_IF"
set_module_description ""
set_module_property "displayName" ""
set_module_property "editable" "true"
set_module_property "group" "Terasic Technologies Inc."
set_module_property "instantiateInSystemModule" "true"
set_module_property "version" "1.0"

# Module parameters

# Interface s1_clock
add_interface "s1_clock" "clock" "sink" "asynchronous"
# Ports in interface s1_clock
add_port_to_interface "s1_clock" "avs_s1_clk_iCLK" "clk"
add_port_to_interface "s1_clock" "avs_s1_reset_n_iRST_N" "reset_n"

# Interface s1
add_interface "s1" "avalon" "slave" "s1_clock"
set_interface_property "s1" "isNonVolatileStorage" "false"
set_interface_property "s1" "burstOnBurstBoundariesOnly" "false"
set_interface_property "s1" "readLatency" "0"
set_interface_property "s1" "readWaitStates" "60"
set_interface_property "s1" "holdTime" "5"
set_interface_property "s1" "printableDevice" "false"
set_interface_property "s1" "readWaitTime" "60"
set_interface_property "s1" "setupTime" "5"
set_interface_property "s1" "addressAlignment" "NATIVE"
set_interface_property "s1" "writeWaitTime" "60"
set_interface_property "s1" "timingUnits" "Nanoseconds"
set_interface_property "s1" "minimumUninterruptedRunLength" "1"
set_interface_property "s1" "isMemoryDevice" "false"
set_interface_property "s1" "linewrapBursts" "false"
set_interface_property "s1" "writeWaitStates" "60"
set_interface_property "s1" "maximumPendingReadTransactions" "0"
# Ports in interface s1
add_port_to_interface "s1" "avs_s1_writedata_iDATA" "writedata"
add_port_to_interface "s1" "avs_s1_readdata_oDATA" "readdata"
add_port_to_interface "s1" "avs_s1_address_iCMD" "address"
add_port_to_interface "s1" "avs_s1_read_n_iRD_N" "read_n"
add_port_to_interface "s1" "avs_s1_write_n_iWR_N" "write_n"
add_port_to_interface "s1" "avs_s1_chipselect_n_iCS_N" "chipselect_n"

# Interface s1_irq
add_interface "s1_irq" "interrupt" "sender" "s1_clock"
set_interface_property "s1_irq" "associatedAddressablePoint" "s1"
# Ports in interface s1_irq
add_port_to_interface "s1_irq" "avs_s1_irq_oINT" "irq"

# Interface s1_export
add_interface "s1_export" "conduit" "start" "s1_clock"
# Ports in interface s1_export
add_port_to_interface "s1_export" "avs_s1_export_ENET_DATA" "export"
add_port_to_interface "s1_export" "avs_s1_export_ENET_CMD" "export"
add_port_to_interface "s1_export" "avs_s1_export_ENET_RD_N" "export"
add_port_to_interface "s1_export" "avs_s1_export_ENET_WR_N" "export"
add_port_to_interface "s1_export" "avs_s1_export_ENET_CS_N" "export"
add_port_to_interface "s1_export" "avs_s1_export_ENET_RST_N" "export"
add_port_to_interface "s1_export" "avs_s1_export_ENET_INT" "export"
add_port_to_interface "s1_export" "avs_s1_export_ENET_CLK" "export"
