# TCL File Generated by Component Editor 7.2 on:
# Fri Oct 05 17:51:07 CST 2007
# DO NOT MODIFY

set_source_file "VGA_NIOS_CTRL.v"
set_module "VGA_NIOS_CTRL"
set_module_description ""
set_module_property "author" "David Wei"
set_module_property "className" "VGA_NIOS_CTRL"
set_module_property "displayName" "Binary_VGA_Controller_IF"
set_module_property "editable" "true"
set_module_property "group" "Terasic Technologies Inc."
set_module_property "instantiateInSystemModule" "true"
set_module_property "version" "1.0"

# Module parameters
add_parameter "RAM_SIZE" "integer" "307200" ""

# Interface s1_clock
add_interface "s1_clock" "clock" "sink" "asynchronous"
# Ports in interface s1_clock
add_port_to_interface "s1_clock" "avs_s1_clk_iCLK" "clk"
add_port_to_interface "s1_clock" "avs_s1_reset_n_iRST_N" "reset_n"

# Interface global_signals_export
add_interface "global_signals_export" "conduit" "start" "asynchronous"
# Ports in interface global_signals_export
add_port_to_interface "global_signals_export" "avs_s1_export_VGA_R" "export"
add_port_to_interface "global_signals_export" "avs_s1_export_VGA_G" "export"
add_port_to_interface "global_signals_export" "avs_s1_export_VGA_B" "export"
add_port_to_interface "global_signals_export" "avs_s1_export_VGA_HS" "export"
add_port_to_interface "global_signals_export" "avs_s1_export_VGA_VS" "export"
add_port_to_interface "global_signals_export" "avs_s1_export_VGA_SYNC" "export"
add_port_to_interface "global_signals_export" "avs_s1_export_VGA_BLANK" "export"
add_port_to_interface "global_signals_export" "avs_s1_export_VGA_CLK" "export"
add_port_to_interface "global_signals_export" "avs_s1_export_iCLK_25" "export"

# Interface s1
add_interface "s1" "avalon" "slave" "s1_clock"
set_interface_property "s1" "isNonVolatileStorage" "false"
set_interface_property "s1" "burstOnBurstBoundariesOnly" "false"
set_interface_property "s1" "readLatency" "0"
set_interface_property "s1" "readWaitStates" "0"
set_interface_property "s1" "holdTime" "0"
set_interface_property "s1" "printableDevice" "false"
set_interface_property "s1" "readWaitTime" "0"
set_interface_property "s1" "setupTime" "0"
set_interface_property "s1" "addressAlignment" "NATIVE"
set_interface_property "s1" "writeWaitTime" "0"
set_interface_property "s1" "timingUnits" "Cycles"
set_interface_property "s1" "minimumUninterruptedRunLength" "1"
set_interface_property "s1" "isMemoryDevice" "false"
set_interface_property "s1" "linewrapBursts" "false"
set_interface_property "s1" "maximumPendingReadTransactions" "0"
# Ports in interface s1
add_port_to_interface "s1" "avs_s1_writedata_iDATA" "writedata"
add_port_to_interface "s1" "avs_s1_readdata_oDATA" "readdata"
add_port_to_interface "s1" "avs_s1_address_iADDR" "address"
add_port_to_interface "s1" "avs_s1_write_iWR" "write"
add_port_to_interface "s1" "avs_s1_read_iRD" "read"
add_port_to_interface "s1" "avs_s1_chipselect_iCS" "chipselect"
